Repository Posxidon/Degree-Flow, pull requests merged in 2025-04, with the labels that each got.

#70 Update TimeTableScraperService.java
  degreeflow-backend/src/main/java/com/degreeflow/service/TimeTableScraperService.java
Labels: update

#71 Update SeatAlertService.java
  degreeflow-backend/src/main/java/com/degreeflow/service/SeatAlertService.java
Labels: update

#72 Update SeatAlertController.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/SeatAlertController.java
Labels: update

#73 fix router issue
  frontend/src/App.js
Labels: bug

#77 unit test cases for seat alert
  degreeflow-backend/src/main/java/com/degreeflow/service/TimeTableScraperService.java
  degreeflow-backend/src/test/java/com/degreeflow/controller/SeatAlertControllerTest.java
  degreeflow-backend/src/test/java/com/degreeflow/service/SeatAlertServiceTest.java
Labels: test

#78 fixed seat alert and homepage
  frontend/src/App.js
  frontend/src/HomePage.js
  frontend/src/index.js
  frontend/src/pages/SeatAlertPage.css
  frontend/src/pages/SeatAlertPage.js
Labels: bug

#80 bug fix
  degreeflow-backend/src/main/java/com/degreeflow/service/TimeTableScraperService.java
Labels: bug

#81 frontend-tests for seat alert
  frontend/src/test/SeatAlertPage.test.js
Labels: test

#82 Changes and unit tests
  degreeflow-backend/src/main/java/com/degreeflow/controller/CourseFilterController.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/RatingController.java
  degreeflow-backend/src/main/java/com/degreeflow/repository/RatingRepository.java
  degreeflow-backend/src/main/java/com/degreeflow/service/RatingService.java
  degreeflow-backend/src/test/java/com/degreeflow/controller/CourseFilterControllerTest.java
  degreeflow-backend/src/test/java/com/degreeflow/controller/RatingControllerTest.java
  degreeflow-backend/src/test/java/com/degreeflow/service/RatingServiceTest.java
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/CourseDifficultyRating/CourseDifficultyRating.css
  frontend/src/components/CourseDifficultyRating/CourseDifficultyRating.js
  frontend/src/components/CourseDifficultyRating/LoginModal/LoginPromptModal.css
  frontend/src/components/CourseDifficultyRating/LoginModal/LoginPromptModal.js
  frontend/src/components/FilterSelection/FilterAppearance.css
  frontend/src/components/FilterSelection/FilterOptions.css
  frontend/src/components/FilterSelection/FilterOptions.js
  frontend/src/components/FilterSelection/FilterPageButtons.js
  frontend/src/components/FilterSelection/FilterSelection.js
  frontend/src/services/CourseApiService.js
  frontend/src/services/RatingApiService.js
  frontend/src/test/CourseDifficultyRating.test.js
Labels: update, test

#85 PDF parsing for transcript
  degreeflow-backend/src/main/java/com/degreeflow/controller/TranscriptController.java
  degreeflow-backend/src/main/java/com/degreeflow/model/TranscriptData.java
  degreeflow-backend/src/main/java/com/degreeflow/repository/TranscriptRepository.java
  degreeflow-backend/src/main/java/com/degreeflow/service/TranscriptParser.java
  degreeflow-backend/src/main/java/com/degreeflow/service/TranscriptService.java
  frontend/src/App.js
  frontend/src/components/pdf-parsing/LegalPopUp.js
  frontend/src/components/pdf-parsing/TranscriptTable.css
  frontend/src/components/pdf-parsing/TranscriptTable.js
  frontend/src/components/pdf-parsing/UploadTranscript.css
  frontend/src/components/pdf-parsing/UploadTranscript.js
Labels: feature

#86 Update package.json
  frontend/package.json
Labels: dependencies

#87 upload-transcript unit tests
  degreeflow-backend/src/main/java/com/degreeflow/service/TranscriptService.java
  degreeflow-backend/src/test/java/com/degreeflow/controller/TranscriptControllerTest.java
  degreeflow-backend/src/test/java/com/degreeflow/service/TranscriptServiceTest.java
  frontend/src/test/SeatAlertPage.test.js
  frontend/src/test/UploadTranscript.test.js
  frontend/src/test/test.pdf
Labels: test

#92 Added Auth0 login component
  .idea/sqldialects.xml
  Documents/Project Plan (2).pdf
  Documents/V&V_group4.pdf
  Documents/poster-gpr4-cap.pdf
  degreeflow-backend/.azure/.gitignore
  degreeflow-backend/.azure/default/connections.xml
  degreeflow-backend/.azure/profiles.xml
  degreeflow-backend/degreeflow-backend.iml
  degreeflow-backend/pom.xml
  degreeflow-backend/src/main/java/com/degreeflow/config/SecurityConfig.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/AuthController.java
  frontend/package.json
  frontend/src/App.js
  frontend/src/Header.js
  frontend/src/HomePage.js
  frontend/src/components/ProtectedData.js
  frontend/src/components/ProtectedRoute.js
  frontend/src/index.js
Labels: feature

#93 Yanchun wang146 patch 2
  degreeflow-backend/src/main/java/com/degreeflow/controller/RatingController.java
  degreeflow-backend/src/test/java/com/degreeflow/controller/RatingControllerTest.java
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/CourseDifficultyRating/CourseDifficultyRating.css
  frontend/src/components/CourseDifficultyRating/CourseDifficultyRating.js
  frontend/src/components/CourseDifficultyRating/LoginModal/LoginPromptModal.js
  frontend/src/components/FilterSelection/FilterAppearance.css
  frontend/src/components/FilterSelection/FilterOptions.js
  frontend/src/components/FilterSelection/FilterWrapper.css
  frontend/src/components/FilterSelection/FilterWrapper.js
  frontend/src/services/CourseApiService.js
  frontend/src/services/RatingApiService.js
Labels: update

#94 updated application.properties and removed .iml file
  degreeflow-backend/degreeflow-backend.iml
  degreeflow-backend/src/main/resources/application.properties
Labels: update

#95 ui fixes
  degreeflow-backend/target/classes/com/degreeflow/controller/TranscriptController.class
  degreeflow-backend/target/classes/com/degreeflow/model/TranscriptData.class
  degreeflow-backend/target/classes/com/degreeflow/repository/TranscriptRepository.class
  degreeflow-backend/target/classes/com/degreeflow/service/PathwayService.class
  degreeflow-backend/target/classes/com/degreeflow/service/TranscriptParser.class
  degreeflow-backend/target/classes/com/degreeflow/service/TranscriptService.class
  degreeflow-backend/target/test-classes/com/degreeflow/controller/TranscriptControllerTest.class
  degreeflow-backend/target/test-classes/com/degreeflow/service/TranscriptServiceTest.class
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/WhatIf/CourseGroupNode.css
  frontend/src/components/WhatIf/CourseGroupNode.js
  frontend/src/components/WhatIf/Node.css
  frontend/src/components/WhatIf/Node.js
  frontend/src/components/WhatIf/WhatIf.js
  frontend/src/components/WhatIf/What_if.css
Labels: bug

#97 fixed json_schedule database duplicate entries error
  degreeflow-backend/src/main/java/com/degreeflow/service/PathwayService.java
  degreeflow-backend/target/classes/com/degreeflow/config/SecurityConfig.class
  degreeflow-backend/target/classes/com/degreeflow/controller/RatingController.class
  degreeflow-backend/target/classes/com/degreeflow/service/PathwayService.class
  degreeflow-backend/target/test-classes/com/degreeflow/controller/RatingControllerTest.class
Labels: bug

#99 deleted .azure folder
  degreeflow-backend/.azure/.gitignore
  degreeflow-backend/.azure/default/connections.xml
  degreeflow-backend/.azure/profiles.xml
Labels: bug

#101 fix auth for seat and pdf
  frontend/src/components/pdf-parsing/UploadTranscript.js
  frontend/src/pages/SeatAlertPage.js
Labels: bug

#102 Update SeatAlertPage.css
  frontend/src/pages/SeatAlertPage.css
Labels: update

#103 Updated index.js and ProtectedRoute.js
  frontend/src/components/ProtectedRoute.js
  frontend/src/index.js
Labels: bug

#104 fixed layout
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/HomePage.css
Labels: bug

#107 What if added back
  frontend/src/App.js
Labels: bug

#109 Added privacy policy page
  frontend/public/files/DegreeFlow_PrivacyPolicy_TermsOfUse_Final.pdf
  frontend/src/App.js
  frontend/src/pages/PrivacyPolicy.css
  frontend/src/pages/PrivacyPolicy.js
Labels: feature

#111 Added Contact Us page
  frontend/src/components/Contact/Contact.css
  frontend/src/components/Contact/Contact.js
Labels: feature

#106 Generate schedule backend 2
  .idea/dbnavigator.xml
  degreeflow-backend/degreeflow-backend.iml
  degreeflow-backend/src/main/java/com/degreeflow/config/SecurityConfig.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/SchedulingController.java
  degreeflow-backend/src/main/java/com/degreeflow/model/JsonSchedule.java
  degreeflow-backend/src/main/java/com/degreeflow/model/Schedule.java
  degreeflow-backend/src/main/java/com/degreeflow/repository/DegreeRepository.java
  degreeflow-backend/src/main/java/com/degreeflow/repository/ScheduleRepository.java
  degreeflow-backend/src/main/java/com/degreeflow/service/PathwayService.java
  degreeflow-backend/src/main/java/com/degreeflow/service/SchedulingService.java
  degreeflow-backend/src/main/resources/application.properties
  degreeflow-backend/src/test/java/com/degreeflow/repository/DegreeRepositoryTest.java
  degreeflow-backend/src/test/java/com/degreeflow/service/PathwayServiceTest.java
  degreeflow-backend/target/classes/application.properties
  degreeflow-backend/target/classes/com/degreeflow/config/SecurityConfig.class
  degreeflow-backend/target/classes/com/degreeflow/controller/SchedulingController.class
  degreeflow-backend/target/classes/com/degreeflow/model/JsonSchedule.class
  degreeflow-backend/target/classes/com/degreeflow/model/Schedule.class
  degreeflow-backend/target/classes/com/degreeflow/repository/DegreeRepository.class
  degreeflow-backend/target/classes/com/degreeflow/repository/ScheduleRepository.class
  degreeflow-backend/target/classes/com/degreeflow/service/PathwayService.class
  degreeflow-backend/target/classes/com/degreeflow/service/SchedulingService.class
  degreeflow-backend/target/test-classes/com/degreeflow/repository/DegreeRepositoryTest.class
  degreeflow-backend/target/test-classes/com/degreeflow/service/PathwayServiceTest.class
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/WhatIf/WhatIf.js
  frontend/src/pages/GenerateSchedule.css
  frontend/src/pages/GenerateSchedule.js
Labels: feature

#114 fixed app.js cuz im an idiot
  frontend/src/App.js
Labels: bug

#113 reflection file
  Documents/Group_4_Reflection.pdf
Labels: documentation

#116 implemented Swagger API for controller classes
  degreeflow-backend/src/main/java/com/degreeflow/config/SecurityConfig.java
  degreeflow-backend/src/main/java/com/degreeflow/config/SwaggerConfig.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/AuthController.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/CourseController.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/CourseFilterController.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/DegreeController.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/RatingController.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/SeatAlertController.java
  degreeflow-backend/src/main/java/com/degreeflow/controller/TranscriptController.java
Labels: documentation, feature

#118 added encryption and fixed homepage
  degreeflow-backend/src/main/java/com/degreeflow/controller/TranscriptController.java
  degreeflow-backend/src/main/java/com/degreeflow/model/TranscriptData.java
  degreeflow-backend/src/main/java/com/degreeflow/service/TranscriptService.java
  degreeflow-backend/src/main/java/com/degreeflow/util/EncryptionUtil.java
  degreeflow-backend/src/main/resources/application.properties
  frontend/src/App.js
  frontend/src/Header.js
  frontend/src/components/pdf-parsing/LegalPopUp.css
  frontend/src/components/pdf-parsing/LegalPopUp.js
  frontend/src/components/pdf-parsing/TranscriptTable.css
  frontend/src/components/pdf-parsing/TranscriptTable.js
  frontend/src/components/pdf-parsing/UploadTranscript.css
  frontend/src/components/pdf-parsing/UploadTranscript.js
  frontend/src/test/UploadTranscript.test.js
Labels: feature

#119 New Docs
  Documents/Project Plan V2.pdf
  Documents/SRS overview V2.pdf
Labels: documentation

#121 added k6 load testing
  degreeflow-backend/pom.xml
  load-tests/degreeflow_k6_test.js
Labels: test

#122 v2
  Documents/Group 04 Design Document v2.pdf
Labels: documentation

#125 Doc/readme
  README.md
Labels: documentation

#124 Appendix - Tells which component does what
  Documents/APPENDIX.pdf
Labels: documentation

#126 new doc
  Documents/V&V document V2.pdf
Labels: documentation
